name: World_CICD
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag Docker image
        run: |
          docker build -t world .
          docker tag world fatemehragh/world:latest
      - name: Push Docker image
        run: docker push fatemehragh/world:latest
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@3
          liara deploy --app="world" --api-token="$LIARA_TOKEN" --detach --port=3000  --image fatemehragh/world:latest
